services:
  view:
    image: view
    build:
      context: ./view
    ports:
      - "5000:5000"
    depends_on:
      - videoservice
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4334
      POSTGRES_DB: AnimeVideo
    volumes:
      - ./AnimeDb.sql:/docker-entrypoint-initdb.d/00-backup.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  videoservice:
    image: videoservice
    build:
      context: ./videoservice
    ports:
      - "5001:5001"
