services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --include-restarting frontend serverinteraction videoservice titleservice searchservice gatewayservice titlerecommendationservice userservice dbupdater
    restart: unless-stopped

  frontend:
    image: ghcr.io/pauk456/frontend:latest
    build:
      context: ./ReactApp 
    ports:
      - "3000:3000"      
    environment:
      - HOST=0.0.0.0      
      - PORT=3000
    depends_on:
      - gatewayservice

  serverinteraction:
    image: ghcr.io/pauk456/serverinteraction:latest
    build:
      context: ./ServerInteraction
    ports:
      - "4999:4999"
    volumes:
      - ./AnimeData:/app/data

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4334
      POSTGRES_DB: AnimeVideo
    volumes:
      - ./AnimeDb.sql:/docker-entrypoint-initdb.d/00-backup.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  videoservice:
    image: ghcr.io/pauk456/videoservice:latest
    build:
      context: ./VideoService
    ports:
      - "5001:5001"
    depends_on:
      - db

  titleservice:
    image: ghcr.io/pauk456/titleservice:latest
    build:
      context: ./TitleService
    ports:
      - "5006:5006"
    depends_on:
      - db
  
  searchdb:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SearchData
    volumes:
      - ./SearchData.sql:/docker-entrypoint-initdb.d/00-backup.sql
      - pg_search_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
      
  searchservice:
    image: ghcr.io/pauk456/searchservice:latest
    build:
      context: ./SearchService
    ports:
      - "5003:5003"
    depends_on:
      - searchdb
 
  gatewayservice:
    image: ghcr.io/pauk456/gatewayservice:latest
    build:
      context: ./GatewayService
    ports:
      - "5004:5004"
    depends_on:
      - titleservice
      - videoservice
      - searchservice

  Dbtitlerecommendationservice:
     image: postgres:17
     environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: 1234
         POSTGRES_DB: TitleRating
     volumes:
         - ./TitleRecommendationData.sql:/docker-entrypoint-initdb.d/00-backup.sql
         - pg_title_recommendation_data:/var/lib/postgresql/data
     ports:
         - "5434:5432"

  titlerecommendationservice:
    image: ghcr.io/pauk456/titlerecommendationservice:latest
    build:
        context: ./TitleRecommendationService
    ports:
       - "5007:5007"
    depends_on:
       - Dbtitlerecommendationservice

  dbuserservice:
     image: postgres:17
     environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: 1234
         POSTGRES_DB: UserService
     volumes:
         - ./UserServiceData.sql:/docker-entrypoint-initdb.d/00-backup.sql
         - pg_user_data:/var/lib/postgresql/data
     ports:
         - "5435:5432"

  userservice:
    image: ghcr.io/pauk456/userservice:latest
    build:
        context: ./UserService
    ports:
       - "5002:5002"
    depends_on:
       - dbuserservice

  dbupdater:
    image: ghcr.io/pauk456/dbupdater:latest
    build:
      context: ./DbUpdater
    depends_on:
      - db
      - titleservice
      - serverinteraction
      - gatewayservice
    environment:
      TitleServiceUrl: "http://titleservice:5006"

volumes:
  pg_data:
  pg_search_data:
  pg_title_recommendation_data:  
  pg_user_data:  
