version: '3.8'

services:
  frontend:
    image: frontend
    build:
      context: ./ReactApp 
    ports:
      - "3000:3000"      
    environment:
      - HOST=0.0.0.0      
      - PORT=3000
    depends_on:
      - gatewayservice

  view:
    image: view
    build:
      context: ./view
    ports:
      - "5000:5000"
    depends_on:
      - videoservice
      - titleservice

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4334
      POSTGRES_DB: AnimeVideo
    volumes:
      - ./AnimeDb.sql:/docker-entrypoint-initdb.d/00-backup.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  videoservice:
    image: videoservice
    build:
      context: ./videoservice
    ports:
      - "5001:5001"
    depends_on:
      - db

  titleservice:
    image: titleservice
    build:
      context: ./titleservice
    ports:
      - "5006:5006"
    depends_on:
      - db
  
  searchdb:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SearchData
    volumes:
      - ./SearchData.sql:/docker-entrypoint-initdb.d/00-backup.sql
      - pg_search_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
      
  searchservice:
    image: searchservice
    build:
      context: ./searchservice
    ports:
      - "5003:5003"
    depends_on:
      - searchdb
 
  gatewayservice:
    image: gateway
    build:
      context: ./gatewayservice
    ports:
      - "5004:5004"
    depends_on:
      - titleservice
      - videoservice

  dbupdater:
    image: dbupdater
    build:
      context: ./dbupdater
    depends_on:
      - db
      - titleservice
    environment:
      TitleServiceUrl: "http://titleservice:5006"

volumes:
  pg_data:
  pg_search_data: