name: Build and Run Tests with Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          version: '8.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose Plugin
        run: |
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-linux-x86_64  -o $DOCKER_CONFIG/cli-plugins/docker-compose
          chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          docker compose version

      - name: Build and start services with Docker Compose
        run: |
          docker compose up -d --build

      - name: Wait for Gateway to be ready
        run: |
          timeout=120
          while [ $timeout -gt 0 ]; do
            curl -s http://localhost:5004/api/Test | grep -q "Hello from Gataway!" && echo "Gateway is UP" && exit 0
            sleep 5
            timeout=$((timeout - 5))
          done
          echo "Timeout waiting for Gateway"
          exit 1

      - name: Restore Test Project
        run: |
          cd TestProjectNUnit
          dotnet restore

      - name: Run Integration Tests
        run: |
          cd TestProjectNUnit
          dotnet test --logger trx --results-directory ./test-results
